#ifndef _HEART_H_
#define _HEART_H_
#include "lcd.h"
void draw_heart(uint8_t x, uint8_t y, uint8_t w)
{
	uint8_t byte;

	lcd_gotoxy(0, 0);
	byte = 0x80;
	lcd_write_data(byte);
	x++;
	byte = 0xC0;
	lcd_write_data(byte);
	x++;
	byte = 0x60;
	lcd_write_data(byte);
	x++;
	byte = 0x30;
	lcd_write_data(byte);
	x++;
	byte = 0x18;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x18;
	lcd_write_data(byte);
	x++;
	byte = 0x30;
	lcd_write_data(byte);
	x++;
	byte = 0x60;
	lcd_write_data(byte);
	x++;
	byte = 0xC0;
	lcd_write_data(byte);
	x++;
	byte = 0x80;
	lcd_write_data(byte);
	byte = 0x80;
	lcd_write_data(byte);
	x++;
	byte = 0xC0;
	lcd_write_data(byte);
	x++;
	byte = 0x60;
	lcd_write_data(byte);
	x++;
	byte = 0x30;
	lcd_write_data(byte);
	x++;
	byte = 0x18;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x18;
	lcd_write_data(byte);
	x++;
	byte = 0x30;
	lcd_write_data(byte);
	x++;
	byte = 0x60;
	lcd_write_data(byte);
	x++;
	byte = 0xC0;
	lcd_write_data(byte);
	x++;
	byte = 0x80;
	lcd_write_data(byte);
	lcd_gotoxy(0, 1);
	byte = 0xFF;
	lcd_write_data(byte);
	lcd_gotoxy(29, 1);
	byte = 0xFF;
	lcd_write_data(byte);
	lcd_gotoxy(1, 2);
	byte = 0x01;
	lcd_write_data(byte);
	x++;
	byte = 0x02;
	lcd_write_data(byte);
	x++;
	byte = 0x04;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x10;
	lcd_write_data(byte);
	x++;
	byte = 0x20;
	lcd_write_data(byte);
	x++;
	byte = 0x40;
	lcd_write_data(byte);
	x++;
	byte = 0x80;
	lcd_write_data(byte);
	lcd_gotoxy(21, 2);
	byte = 0x80;
	lcd_write_data(byte);
	x++;
	byte = 0x40;
	lcd_write_data(byte);
	x++;
	byte = 0x20;
	lcd_write_data(byte);
	x++;
	byte = 0x10;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x04;
	lcd_write_data(byte);
	x++;
	byte = 0x02;
	lcd_write_data(byte);
	x++;
	byte = 0x01;
	lcd_write_data(byte);
	lcd_gotoxy(9, 3);
	byte = 0x01;
	lcd_write_data(byte);
	x++;
	byte = 0x02;
	lcd_write_data(byte);
	x++;
	byte = 0x04;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x10;
	lcd_write_data(byte);
	x++;
	byte = 0x20;
	lcd_write_data(byte);
	lcd_gotoxy(15, 3);
	byte = 0x20;
	lcd_write_data(byte);
	x++;
	byte = 0x10;
	lcd_write_data(byte);
	x++;
	byte = 0x08;
	lcd_write_data(byte);
	x++;
	byte = 0x04;
	lcd_write_data(byte);
	x++;
	byte = 0x02;
	lcd_write_data(byte);
	x++;
	byte = 0x01;
	lcd_write_data(byte);
 	while (--w);
}
#endif
